version: '3.7'

services:
  api:
    build: .
    ports:
      - 8080:3000
    volumes:
      - .:/api:cached
  rdb:
    image: postgres:12
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=example
    ports:
      - 5432:5432
